### ISSUE TITLE
Galería de Fotos DGCali 2018

### ISSUE THREAD

**Issue by EllaQuimica** [humitos/argentinaenpython.com#139]
Hola @humitos, estamos pendientes de generar la galería del evento de Django Girls Cali. Te adjunto el link de las fotos https://photos.google.com/share/AF1QipPgnsFowfeO63nkxCuxSCj06PrZDwZE8UQeInHaXtQvzUSNabNJNVBarWng62s20A?key=N3E1d1RsWjBUcmxTM1hFZk5nMTYzV184UGloOEZB

**Comment by humitos** [comment]
Subidas en https://argentinaenpython.com/galeria/django-girls-cali/
