### ISSUE TITLE
Blogpost de PyCon Japon en Prensa

### ISSUE THREAD

**Issue by humitos** [humitos/argentinaenpython.com#154]
Hay que incluir esta página: https://pyconjp.blogspot.com/2018/08/day1-about-keynote-speaker.html

![screenshot_2018-08-07 pycon jp 2018 1 about the keynote speaker on the first day](https://user-images.githubusercontent.com/244656/43799437-ef40ab96-9a63-11e8-8182-d4d4a7f1a13c.png)

**Comment by EllaQuimica** [comment]
@humitos esto ya lo podemos dar por cerrado, cierto?

**Comment by humitos** [comment]
@EllaQuimica Sí!

Si en PR que abrís le ponés: `Closes #154`, por ejemplo, cuando se hace merge de la PR el issue se cierra automáticamente.

Más doc: https://help.github.com/articles/closing-issues-using-keywords/
