### ISSUE TITLE
Galería de Fotos - DGirls Pereira 2018 

### ISSUE THREAD

**Issue by EllaQuimica** [humitos/argentinaenpython.com#174]
@humitos podrías ayudarnos creando la galería de fotos del evento de pereira 2018, este es el link https://drive.google.com/drive/folders/15IimUV3jQqfDHuG5-xOKWd_JwKYu0S8I?usp=sharing

**Comment by humitos** [comment]
Publicado en https://argentinaenpython.com/galeria/django-girls-pereira/2018/
