### ISSUE TITLE
Galería de Fotos - DGirls Bogotá 2018

### ISSUE THREAD

**Issue by EllaQuimica** [humitos/argentinaenpython.com#175]
@humitos puedes ayudarnos a generar la galería de fotos del evento de Bogotá, este es el link https://drive.google.com/open?id=1ERjlEYpN7HV9FtA5gh7LCaAovU2tQxI2

**Comment by humitos** [comment]
Publicado en https://argentinaenpython.com/galeria/django-girls-bogota/2018/
