### ISSUE TITLE
Mejorar sección de ciencia en Quiero aprender Python

### ISSUE THREAD

**Issue by humitos** [humitos/argentinaenpython.com#26]
En nuestra sección de "Soy científico y quiero analizar mis datos", https://argentinaenpython.com/quiero-aprender-python/, nos gustaría tener más documentación y motivar a la gente a hacer diferentes cosas, quizás con ejemplo, quizás con un párrafo que mencione ejemplos o similar.

cc @juanlu001

**Comment by Juanlu001** [comment]
Ahí va :)
