### ISSUE TITLE
Difusion de nuestra investigacion de Desaparecidos en Democracia Argentina

### ISSUE THREAD

**Issue by cancerbero-arg** [humitos/argentinaenpython.com#63]
Sentite libre de borrar este issue, solo buscamos divulgar nuestra investigación.
https://cancerbero-arg.github.io/desaparecidos-en-democracia-argentina/

**Comment by humitos** [comment]
Gracias por tu issue. Si bien entiendo y comparto la causa, este proyecto no está relacionado con la temática.

Muchas gracias.
